name: Bandit Scan
on: [push, pull_request]

jobs:
  bandit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bandit Scan
        uses: jpetrucciani/bandit-check@master
        with:
          path: "."
